apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: kong-{{KONG_CONTEXT}}
spec:
  template:
    metadata:
      name: kong-migrations
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - kong migrations bootstrap
        env:
        - name: KONG_PG_PASSWORD
          value: kong
        - name: KONG_PG_HOST
          value: postgres
        - name: KONG_PG_PORT
          value: "5432"
        image: kong:3.1
        name: kong-migrations
      initContainers:
      - command:
        - /bin/bash
        - -c
        - until timeout 1 bash 9<>/dev/tcp/${KONG_PG_HOST}/${KONG_PG_PORT}; do echo
          'waiting for db'; sleep 1; done
        env:
        - name: KONG_PG_HOST
          value: postgres
        - name: KONG_PG_PORT
          value: "5432"
        image: kong:3.1
        name: wait-for-postgres
      restartPolicy: OnFailure