apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: jwt-keycloak-{{KONG_CONTEXT}}
  annotations:
    kubernetes.io/ingress.class: kong-{{KONG_CONTEXT}}
  labels:
    global: "true"
config:
  allowed_iss: 
    - {{KEYCLOAK_ISS_URL}}
plugin: jwt-keycloak
