apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: kong-serviceaccount
  name: kong-serviceaccount-token
  namespace: kong-{{KONG_CONTEXT}}
type: kubernetes.io/service-account-token