apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong-{{KONG_CONTEXT}}
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ingress-kong
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kong-validation-webhook
  namespace: kong-{{KONG_CONTEXT}}
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingress-kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-api
  namespace: kong-{{KONG_CONTEXT}}
spec:
  ports:
  - name: kong-admin-api
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: kong-admin-api-ssl
    port: 8444
    protocol: TCP
    targetPort: 8444
  selector:
    app: ingress-kong

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kong-{{KONG_CONTEXT}}
spec:
  ports:
  - name: pgql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
---